export const ROCK = 'rock'
export const PAPER = 'paper'
export const SCISSORS = 'scissors'
export const USER_SCORE = 'USER_SCORE'
export const COMPUTER_SCORE = 'COMPUTER_SCORE'
export const DRAW_SCORE = 'DRAW_SCORE'
export const CLEAR_TOGGLES = 'CLEAR_TOGGLES'
export const USER_CHOICE = 'USER_CHOICE'
export const COMPUTER_CHOICE = 'COMPUTER_CHOICE'
export const START = 'START'
export const LOADING = 'LOADING'
export const RESTART = 'RESTART'
export const END = 'END'

